### ISSUE TITLE
Move repository to final location

### ISSUE THREAD

**Issue by leesdolphin** [LABHR/hatrack#11]
Move the repository so the URL on github.io is consistent with other LABHR projects.

**Comment by glasnt** [comment]
So the choices we have are: 
 * github
 * hatrack

Option 1 matches the StackOverflow, Wikipedia repos

Option 2 I think makes for a better URL (labhr.github.io/hatrack).

Thanks to the wonder of the 301 redirects for renaming repos, we aren't locked to anything in particular. 

What's your opinion, @leesdolphin?

**Comment by leesdolphin** [comment]
My personal preference would be 'hatrack'; it would give a readable URL and keep the repo's name sane, I don't think having a repo named 'github' would be helpful.

**Comment by glasnt** [comment]
:shipit: I'll rename the repo now

**Comment by glasnt** [comment]
Done. Be sure to either re-clone the repo under the new name, or update the `.git/config` to point to the new location.

**Comment by glasnt** [comment]
p.s. I've [added a redirect](https://github.com/LABHR/labhr.github.io/commit/5a4de80337b3ae35bcc4c61db09165f808e36498) on the labhr.github.io domain to ensure that anyone going to js-hatrack is redirected to hatrack. It'll work for base urls, unsure if the hash will stick, but i'm sure I can hack that in with a bit of JS if it becomes an issue.

**Comment by glasnt** [comment]
I've also updated the package.json, bower.json, and index.html references to use the new repo name. You'll need to pull these updates to prevent merge conflicts
